routes/web.php
<?php

use App\Mail\MyTestMail;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\bookController;
use App\Http\Controllers\homeController;
use App\Http\Controllers\TestController;
use App\Http\Controllers\tranController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\FrontController;
use App\Http\Controllers\priceController;
use App\Http\Controllers\autherController;
use App\Http\Controllers\genresController;
use App\Http\Controllers\HelperController;
use App\Http\Controllers\searchController;
use App\Http\Controllers\ArticleController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\SiteMapController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\TrafficsController;
use App\Http\Controllers\RedirectionController;
use App\Http\Controllers\NotificationsController;






Auth::routes();
//Route::get('/', function () {return view('front.index');})->name('home');
//Route::get('/test',[TestController::class,'index']);
Route::get('/',[HomeController::class,'index'])->name('home');

Route::prefix('admin')->middleware(['auth','CheckRole:ADMIN|EDITOR','ActiveAccount'])->name('admin.')->group(function () {
    Route::get('/',[AdminController::class,'index'])->name('index');


    //Route::get('/profile',[AdminController::class,'upload_image']);
    
    Route::resource('contacts',ContactController::class)->middleware(['CheckRole:ADMIN|EDITOR']);
    Route::resource('users',UserController::class)->middleware(['CheckRole:ADMIN|EDITOR']);
    Route::resource('articles',ArticleController::class);
    Route::resource('book',bookController::class);
    Route::resource('auther',autherController::class);
    Route::resource('genres',genresController::class);
    Route::resource('categories',CategoryController::class);
    Route::resource('transaction',tranController::class);
    Route::resource('price',priceController::class);
    Route::resource('redirections',RedirectionController::class)->middleware(['CheckRole:ADMIN|EDITOR']);

    Route::get('pay',[tranController::class,'pay'])->name('pay.index');
    Route::get('employ',[UserController::class,'emp'])->name('emp.index');
    Route::get('my_tran/{id}',[tranController::class,'my_tran'])->name('my_tran');
    Route::get('traffics',[TrafficsController::class,'index'])->name('traffics.index');
    Route::get('traffics/{traffic}/logs',[TrafficsController::class,'logs'])->name('traffics.logs');
    Route::get('error-reports',[TrafficsController::class,'error_reports'])->name('traffics.error-reports');
    Route::get('error-reports/{report}',[TrafficsController::class,'error_report'])->name('traffics.error-report');

    Route::prefix('upload')->name('upload.')->group(function(){
        Route::post('/image',[HelperController::class,'upload_image'])->name('image');
        Route::post('/file',[HelperController::class,'upload_file'])->name('file');
        Route::post('/remove-file',[HelperController::class,'remove_files'])->name('remove-file');
    });
    Route::prefix('profile')->name('profile.')->group(function () {
        Route::get('/',[ProfileController::class,'index'])->name('index');
        Route::get('/edit',[ProfileController::class,'edit'])->name('edit');
        Route::put('/update',[ProfileController::class,'update'])->name('update');
        Route::put('/update-password',[ProfileController::class,'update_password'])->name('update-password');
        Route::put('/update-email',[ProfileController::class,'update_email'])->name('update-email');
    });
    Route::prefix('notifications')->name('notifications.')->group(function () {
        Route::get('/',[NotificationsController::class,'index'])->name('index');
        Route::get('/ajax',[NotificationsController::class,'notifications_ajax'])->name('ajax');
        Route::post('/see',[NotificationsController::class,'notifications_see'])->name('see');
    });
    Route::prefix('settings')->name('settings.')->group(function () {
        Route::get('/',[SettingController::class,'index'])->name('index');
        Route::put('/update',[SettingController::class,'update'])->name('update');
    });
});


Route::get('blocked',[HelperController::class,'blocked_user'])->name('blocked');
Route::get('robots.txt',[HelperController::class,'robots']);
Route::get('manifest.json',[HelperController::class,'manifest']);
Route::get('sitemap.xml',[SiteMapController::class,'sitemap']);
Route::get('sitemaps/links','SiteMapController@custom_links');
Route::get('sitemaps/{name}/{page}/sitemap.xml',[SiteMapController::class,'viewer']);


//pages
Route::view('about','front.pages.about');
Route::view('privacy','front.pages.privacy');
Route::view('terms','front.pages.terms');
Route::view('contact','front.pages.contact');
Route::get('article/{article}',[FrontController::class,'article'])->name('article.show');
Route::get('blog',[FrontController::class,'blog'])->name('blog');
Route::post('contact',[FrontController::class,'contact_post'])->name('contact-post');

//--------------------------- search ---------------------------
Route::get('/book/search',[bookController::class,'search'])->name('book.search');
Route::get('search/{id}',[searchController::class,'search'])->name('search');
////////////
Route::put('/users.approve/{id}',[UserController::class,'approve'])->name('admin.users.approve');
// ------------------------------------------------------------

Route::get('changeStatus',[tranController::class,'changeStatus']);

app/Models/Redirection.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Redirection extends Model
{
    use HasFactory;
    public $guarded=['id','created_at','updated_at'];
    public function user(){
        return $this->belongsTo(\App\Models\User::class);
    }
}

app/Http/Controllers/RedirectionController.php
<?php

namespace App\Http\Controllers;

use App\Models\Redirection;
use Illuminate\Http\Request;

class RedirectionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $redirections =  Redirection::where(function($q)use($request){
            if($request->id!=null)
                $q->where('id',$request->id);
            if($request->q!=null)
                $q->where('url','LIKE','%'.$request->q.'%')->orWhere('new_url','LIKE','%'.$request->q.'%');
        })->orderBy('id','DESC')->paginate();
        return view('admin.redirections.index',compact('redirections'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.redirections.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'url'=>"required|url",
            'new_url'=>"required|url",
            'code'=>"required|numeric|in:301,302",
        ]);
        Redirection::create([
            'user_id'=>auth()->user()->id,
            'url'=>$request->url,
            'new_url'=>$request->new_url,
            'code'=>$request->code,
        ]);
        flash()->success('تم إضافة التحويل بنجاح','عملية ناجحة');
        return redirect()->route('admin.redirections.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Redirection  $redirection
     * @return \Illuminate\Http\Response
     */
    public function show(Redirection $redirection)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Redirection  $redirection
     * @return \Illuminate\Http\Response
     */
    public function edit(Redirection $redirection)
    {
        if(!auth()->user()->has_access_to('update',$redirection))abort(403);
        return view('admin.redirections.edit',compact('redirection'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Redirection  $redirection
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Redirection $redirection)
    {
        if(!auth()->user()->has_access_to('update',$redirection))abort(403);
        $request->validate([
            'url'=>"required|url",
            'new_url'=>"required|url",
            'code'=>"required|numeric|in:301,302",
        ]);
        $redirection->update([
            'url'=>$request->url,
            'new_url'=>$request->new_url,
            'code'=>$request->code,
        ]);
        flash()->success('تم تحديث التحويل بنجاح','عملية ناجحة');
        return redirect()->route('admin.redirections.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Redirection  $redirection
     * @return \Illuminate\Http\Response
     */
    public function destroy(Redirection $redirection)
    {
        if(!auth()->user()->has_access_to('delete',$redirection))abort(403);
        $redirection->delete();
        flash()->success('تم حذف التحويل بنجاح','عملية ناجحة');
        return redirect()->route('admin.redirections.index');
    }
}

resources/views/admin/redirections/create.blade.php
@extends('layouts.admin')
@section('content')
<div class="col-12 p-3">
	<div class="col-12 col-lg-12 p-0 ">
	 
		
		<form id="validate-form" class="row" enctype="multipart/form-data" method="POST" action="{{route('admin.redirections.store')}}">
		@csrf 
		<div class="col-12 col-lg-8 p-0 main-box">
			<div class="col-12 px-0">
				<div class="col-12 px-3 py-3">
				 	<span class="fas fa-info-circle"></span> إضافة جديد
				</div>
				<div class="col-12 divider" style="min-height: 2px;"></div>
			</div>
			<div class="col-12 p-3 row">
			
				<div class="col-12 col-lg-6 p-2">
					<div class="col-12">
						الرابط القديم
					</div>
					<div class="col-12 pt-3">
						<input type="url" name="url" required  class="form-control" value="{{old('url')}}" >
					</div>
				</div>

				<div class="col-12 col-lg-6 p-2">
					<div class="col-12">
						الرابط الجديد
					</div>
					<div class="col-12 pt-3">
						<input type="text" name="new_url" required  class="form-control"  value="{{old('new_url')}}" >
					</div>
				</div> 
				<div class="col-12 col-lg-6 p-2">
					<div class="col-12">
						نوع التحويل
					</div>
					<div class="col-12 pt-3">
						<select name="code" required class="form-control">
							<option value selected disabled hidden>إحتر نوع التحويل</option>
							<option value="301" @if(old('code')=="301") selected @endif>دائم</option>
							<option value="302" @if(old('code')=="302") selected @endif>مؤقت</option>
						</select>
					</div>
				</div> 

			</div>
 
		</div>
		 
		<div class="col-12 p-3">
			<button class="btn btn-success" id="submitEvaluation">حفظ</button>
		</div> 
		</form>
	</div>
</div>
@endsection

resources/views/admin/redirections/edit.blade.php
@extends('layouts.admin')
@section('content')
<div class="col-12 p-3">
	<div class="col-12 col-lg-12 p-0 ">
	 
		
		<form id="validate-form" class="row" enctype="multipart/form-data" method="POST" action="{{route('admin.redirections.update',$redirection)}}">
		@csrf
		@method("PUT")
		<div class="col-12 col-lg-8 p-0 main-box">
			<div class="col-12 px-0">
				<div class="col-12 px-3 py-3">
				 	<span class="fas fa-info-circle"></span> تعديل رابط تحويل
				</div>
				<div class="col-12 divider" style="min-height: 2px;"></div>
			</div>
			<div class="col-12 p-3 row">
			
				<div class="col-12 col-lg-6 p-2">
					<div class="col-12">
						الرابط القديم
					</div>
					<div class="col-12 pt-3">
						<input type="url" name="url" required  class="form-control" value="{{$redirection->url}}" >
					</div>
				</div>

				<div class="col-12 col-lg-6 p-2">
					<div class="col-12">
						الرابط الجديد
					</div>
					<div class="col-12 pt-3">
						<input type="text" name="new_url" required  class="form-control"  value="{{$redirection->new_url}}" >
					</div>
				</div> 
				<div class="col-12 col-lg-6 p-2">
					<div class="col-12">
						نوع التحويل
					</div>
					<div class="col-12 pt-3">
						<select name="code" required class="form-control">
							<option value selected disabled hidden>إحتر نوع التحويل</option>
							<option value="301" @if($redirection->code=="301") selected @endif>دائم</option>
							<option value="302" @if($redirection->code=="302") selected @endif>مؤقت</option>
						</select>
					</div>
				</div> 

			</div>
 
		</div>
		 
		<div class="col-12 p-3">
			<button class="btn btn-success" id="submitEvaluation">حفظ</button>
		</div> 
		</form>
	</div>
</div>
@endsection

resources/views/admin/redirections/index.blade.php
@extends('layouts.admin')
@section('content')
<div class="col-12 p-3">
	<div class="col-12 col-lg-12 p-0 main-box">
	 
		<div class="col-12 px-0">
			<div class="col-12 p-0 row">
				<div class="col-12 col-lg-4 py-3 px-3">
					<span class="fas fa-redirections"></span> التحويلات
				</div>
				<div class="col-12 col-lg-4 p-2">
				</div>
				<div class="col-12 col-lg-4 p-2 text-lg-end">
					<a href="{{route('admin.redirections.create')}}">
					<span class="btn btn-primary"><span class="fas fa-plus"></span> إضافة جديد</span>
					</a>
				</div>
			</div>
			<div class="col-12 divider" style="min-height: 2px;"></div>
		</div>

		<div class="col-12 py-2 px-2 row">
			<div class="col-12 col-lg-4 p-2">
				<form method="GET">
					<input type="text" name="q" class="form-control" placeholder="بحث ... ">
				</form>
			</div>
		</div>
		<div class="col-12 p-3" style="overflow:auto">
			<div class="col-12 p-0" style="min-width:1100px;">
				
			
			<table class="table table-bordered  table-hover">
				<thead>
					<tr>
						<th>#</th>
						<th>الرابط القديم</th>
						<th>الرابط الجديد</th>
						<th>نوع التحويل</th>
						<th>تحكم</th>
					</tr>
				</thead> 

				<tbody>
					@foreach($redirections as $redirection)
					<tr>
						<td>{{$redirection->id}}</td>
						<td>{{urldecode($redirection->url)}}</td>
						<td>{{urldecode($redirection->new_url)}}</td>
						<td>
							@if($redirection->code==302)
							مؤقت
							@else
							دائم
							@endif
						</td>
						<td style="width: 180px;">
							@if(auth()->user()->has_access_to('update',$redirection))
							<a href="{{route('admin.redirections.edit',$redirection)}}">
							<span class="btn  btn-outline-success btn-sm font-1 mx-1">
								<span class="fas fa-wrench "></span> تحكم
							</span>
							</a>
							@endif
							@if(auth()->user()->has_access_to('delete',$redirection))
							<form method="POST" action="{{route('admin.redirections.destroy',$redirection)}}" class="d-inline-block">@csrf @method("DELETE")
								<button class="btn  btn-outline-danger btn-sm font-1 mx-1" onclick="var result = confirm('هل أنت متأكد من عملية الحذف ؟');if(result){}else{event.preventDefault()}">
									<span class="fas fa-trash "></span> حذف
								</button>
							</form>
							@endif
						</td>
					</tr>
					@endforeach
				</tbody>
			</table>
			</div>
		</div>
		<div class="col-12 p-3">
			{{$redirections->appends(request()->query())->render()}}
		</div>
	</div>
</div>
@endsection